apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  namespace: default   
type: Opaque
data:
  CLOUDANT_URL: aHR0cHM6Ly9lMDE2ZGNiNi1kNzkzLTQyMWItYThkYS05ZDc3YmM3ZWQ2ODUtYmx1ZW1peC5jbG91ZGFudG5vc3FsZGIuYXBwZG9tYWluLmNsb3Vk
  CLOUDANT_APIKEY: SkhVa19JaHRZTDl6dW50c2kycHdjMkVBbTNENmZNMGc1TzVTTEU5UHhQamE=